package main;

public enum RequestResponse {
    //requests
    REGISTRATION,
    LOG_IN,
    GET_CHAT_NAMES,
    EXIT,
    CREATE_CHAT,
    SET_CURRENT_CHAT,
    GET_CHAT_MESSAGE,
    SEND_MESSAGE,
    UPDATE_MESSAGES,
    GET_MEMBERS_NAME,
    //responses
    SUCCESSFUL_REGISTRATION,
    SUCCESSFUL_LOGIN, LOGIN_ERROR,
    MEMBERS_NAME, UPDATE_CHATS
}
